model:
  NAME: ext.DGCNN
  num_classes: 17
  emb_dims: 1000
  k: 6
  num_channels: 15
  dropout: 0
train:
  losses: []
dataset:
  jaw: upper
  image: False
  depth: False
  decimated: True
  mesh_feature_select: [xyz]
  transform: False
dataloader:
  batch_size: 16
  num_workers: 8