seed: 42
model:
  NAME: MeshSegNet
  num_classes: 17
train:
  epochs: 70
  accelerator: gpu
  devices: 1
  ddp: False
  precision: bf16-mixed
  accumulate_grad_batches: 1
  losses: [Dice]
  losses_weights: [1]
  optimizer: 
    NAME: AdamW
    lr: 1e-3
    auto_lr: False
    weight_decay: 1e-5
  scheduler:
    NAME: CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 1e-9
dataset:
  csv_path: formatted_data/teeth3ds.csv
  train_val_ratio: 0.8
  jaw: both
  image: False
  depth: False
  decimated: True
  mesh_feature_select: [xyz,xyz3,norm]
  transform: False
  cached_A_S_L: True
dataloader:
  batch_size: 4
  auto_batch: False
  num_workers: 4
logger:
  log_every_n_steps: 10